# Generated by Django 3.1.4 on 2020-12-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('game_description', models.TextField(max_length=2000)),
                ('game_category', models.TextField(max_length=2000)),
                ('game_rule', models.TextField(max_length=2000)),
                ('game_created_date', models.DateField(blank=True, null=True)),
                ('game_rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
            ],
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(help_text='Name of game collection', max_length=200)),
                ('collection_created_date', models.DateField(blank=True, null=True)),
                ('collection_description', models.TextField(max_length=2000)),
                ('collection_games', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalogue.game')),
            ],
        ),
    ]
