# Generated by Django 3.1.4 on 2020-12-09 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecollection',
            name='collection_games',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique game identifier Id', unique=True),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='collection_games_id',
            field=models.ManyToManyField(help_text='Games belonging to a Collection', to='game_catalogue.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.CharField(max_length=200),
        ),
    ]
