# Generated by Django 3.1.4 on 2020-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.CharField(max_length=200),
        ),
    ]
