# Generated by Django 3.1.4 on 2020-12-09 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0002_auto_20201209_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecollection',
            name='collection_games_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_catalogue.gamecollection'),
        ),
    ]
