# Generated by Django 3.1.4 on 2020-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0002_auto_20201209_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecollection',
            name='collection_games',
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='collection_games',
            field=models.ManyToManyField(help_text='Games belonging to a Collection', to='game_catalogue.Game'),
        ),
    ]
