# Generated by Django 3.1.4 on 2020-12-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0005_gamecollection_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecollection',
            old_name='borrower',
            new_name='owner',
        ),
    ]
