# Generated by Django 3.1.4 on 2020-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0006_auto_20201210_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_collection',
        ),
        migrations.AddField(
            model_name='game',
            name='game_collection',
            field=models.ManyToManyField(help_text='Game collection Game belongs to', to='game_catalogue.GameCollection'),
        ),
    ]
