# Generated by Django 3.1.4 on 2020-12-10 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0007_auto_20201210_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollection',
            name='collection_created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
