# Generated by Django 3.1.4 on 2020-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0008_auto_20201210_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
