# Generated by Django 3.1.4 on 2020-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0010_auto_20201210_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
    ]
