# Generated by Django 3.1.4 on 2020-12-10 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_catalogue', '0011_auto_20201210_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
